# Generated by Django 5.0.2 on 2024-03-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('priority', models.IntegerField()),
                ('del_status', models.IntegerField(choices=[('0', 'delete'), ('1', 'live')], default=1)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('updat_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
